local icons = {}

icons.layout = {
  List = "•",
  Tab = "→",
  Wrap = "↪",
}

icons.widget = {
  Active = "",
  Branch = "",
  Command = "",
  Config = "",
  Error = "",
  Event = "",
  Filetype = "",
  Import = "",
  Inactive = "",
  Keymap = "",
  Lazy = "",
  Loading = "",
  Nesting = "",
  Plugin = "",
  Ready = "",
  Runtime = "",
  Source = "",
  Start = "",
  Task = "",
  Telescope = "",
  Warning = "",
}

icons.kind = {
  Array = "",
  Boolean = "",
  Class = "",
  Color = "",
  Constant = "",
  Constructor = "",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "",
  File = "",
  Folder = "",
  Function = "",
  Interface = "",
  Key = "",
  Keyword = "",
  Method = "",
  Module = "",
  Namespace = "",
  Null = "",
  Number = "",
  Object = "",
  Operator = "",
  Package = "",
  Property = "",
  Reference = "",
  Snippet = "",
  String = "",
  Struct = "",
  Text = "",
  TypeParameter = "",
  Unit = "",
  Value = "",
  Variable = "",
}

return icons
