local icons = {}

icons.layout = {
  List = "•",
  Tab = "→",
  Wrap = "↪",
}

icons.widget = {
  AngleRight = "",
  Archive = "",
  Bed = "",
  Bolt = "",
  ChevronRight = "",
  CircleFill = "",
  CircleStroke = "",
  Clipboard = "",
  Code = "",
  Ellipsis = "",
  Error = "",
  Fire = "",
  Flask = "",
  Fork = "",
  Gear = "",
  HeartBeat = "",
  Keyboard = "",
  PaperClip = "",
  Play = "",
  Usd = "",
  Vim = "",
  Warning = "",
}

icons.kind = {
  Array = "",
  Boolean = "",
  Class = "",
  Color = "",
  Constant = "",
  Constructor = "",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "",
  File = "",
  Folder = "",
  Function = "",
  Interface = "",
  Key = "",
  Keyword = "",
  Method = "",
  Module = "",
  Namespace = "",
  Null = "",
  Number = "",
  Object = "",
  Operator = "",
  Package = "",
  Property = "",
  Reference = "",
  Snippet = "",
  String = "",
  Struct = "",
  Text = "",
  TypeParameter = "",
  Unit = "",
  Value = "",
  Variable = "",
}

return icons
